[package]
name = "coapable"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.1"
coap-lite = "0.13.3"
thiserror = "2.0.18"
rand = "0.9"
tokio = { version = "1.49.0", features = ["full", "test-util"] }
liboscore = "0.2.4"
